version: '3'

services:    
  back:
    image: examen-cote-serveur-sp-2223:latest
    build: .
    environment:
      - NODE_ENV=production
      - DB_URL=mongodb://mongo
    ports:
      - "8090:8090"
    networks:
      - node2223sp
    depends_on:
      - mongo
  mongo:
    image: mongo:5
    ports:
      - "8091:27017"
    networks:
      - node2223sp
    volumes:
      - db:/data/db

volumes:
  db:
networks:
  node2223sp: